import { PrismaLibSql } from "@prisma/adapter-libsql";
import { PrismaClient } from "./app/generated/prisma/client.ts";

const adapter = new PrismaLibSql({
  url: "libsql://cursos-db-monrodolfo2020.aws-us-east-1.turso.io",
  authToken: "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODAyODQ2MTksImlkIjoiMDE5ZTgxMzctMWEwMS03MDQ2LWI0MTYtOGUyOTA5MDBkNDg4IiwicmlkIjoiMjVjYjg2NGItYmFhNi00ODVhLWFmZjItYTU1MmZlYTAzMGI4In0.kVlvb3D-9I3aOavdZ8moaM7UQGmwcsTGtNFvGqRu03GT6mG6X_ovn4PhPi5EFRcodVGXmFnQ5Bd2YMxEaIr_Bw",
});
const prisma = new PrismaClient({ adapter } as any);

const BASE = "/videos/curso-automatizacion";

const lessons = [
  // ── MÓDULO 0 — Bienvenida y Orientación ──────────────────────────────
  {
    order: 1,
    title: "¿En qué mundo industrial vivimos?",
    description: "Introducción al mundo de la automatización. Descubre qué es, por qué importa, las industrias donde se aplica y la ruta del curso.",
    durationSec: 300,
    videoPath: `${BASE}/modulo-0-bienvenida/Video Módulo 0.html`,
  },
  {
    order: 2,
    title: "¿Qué es la automatización y qué no es?",
    description: "Desmitifica la automatización: sus límites reales, diferencias con la robótica y cuándo conviene automatizar un proceso.",
    durationSec: 240,
    videoPath: `${BASE}/modulo-0-bienvenida/Clase 2 - Qué es la automatización.html`,
  },
  {
    order: 3,
    title: "Los personajes del mundo industrial",
    description: "Conoce los roles clave: instrumentista, operador, ingeniero de proceso y de control. Entiende cómo colaboran en planta.",
    durationSec: 240,
    videoPath: `${BASE}/modulo-0-bienvenida/Clase 3 - Los personajes.html`,
  },
  {
    order: 4,
    title: "Ruta de aprendizaje del curso",
    description: "Mapa visual de los 4 módulos: fundamentos, instrumentación, sensores y control. Sabrás exactamente a dónde vas.",
    durationSec: 180,
    videoPath: `${BASE}/modulo-0-bienvenida/Clase 4 - Ruta de aprendizaje.html`,
  },
  {
    order: 5,
    title: "Herramientas del curso",
    description: "Software, simuladores y recursos que usarás a lo largo del curso: draw.io, Tinkercad, PDFs de normas y más.",
    durationSec: 180,
    videoPath: `${BASE}/modulo-0-bienvenida/Clase 5 - Herramientas.html`,
  },
  {
    order: 6,
    title: "Glosario base",
    description: "Los 20 términos que debes dominar antes de empezar: proceso, lazo, señal, transmisor, controlador, actuador y más.",
    durationSec: 240,
    videoPath: `${BASE}/modulo-0-bienvenida/Clase 6 - Glosario base.html`,
  },
  {
    order: 7,
    title: "Conoce una planta industrial real",
    description: "Tour visual por una planta real: identifica dónde viven los instrumentos, las tuberías de proceso y la sala de control.",
    durationSec: 300,
    videoPath: `${BASE}/modulo-0-bienvenida/Clase 7 - Planta industrial real.html`,
  },
  // ── MÓDULO 1 — Fundamentos de Física y Electricidad ──────────────────
  {
    order: 8,
    title: "Unidades del SI aplicadas a la industria",
    description: "Presión en Pa y bar, temperatura en °C y K, caudal en m³/h y más. Las unidades que verás todos los días en planta.",
    durationSec: 300,
    videoPath: `${BASE}/modulo-1-fundamentos/Clase 1.1 - Unidades del SI.html`,
  },
  {
    order: 9,
    title: "Magnitudes físicas industriales",
    description: "Temperatura, presión, nivel y caudal: las cuatro variables que la instrumentación mide y controla en todo proceso.",
    durationSec: 300,
    videoPath: `${BASE}/modulo-1-fundamentos/Clase 1.2 - Magnitudes fisicas.html`,
  },
  {
    order: 10,
    title: "Ley de Ohm y circuitos básicos",
    description: "V = IR en contexto industrial: lazos de corriente 4-20 mA, caídas de tensión en cables y protección de instrumentos.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-1-fundamentos/Clase 1.3 - Ley de Ohm.html`,
  },
  {
    order: 11,
    title: "Corriente continua vs alterna",
    description: "Por qué los instrumentos usan DC 24 V, cuándo aparece el AC y cómo distinguirlos en el tablero de control.",
    durationSec: 300,
    videoPath: `${BASE}/modulo-1-fundamentos/Clase 1.4 - AC vs DC.html`,
  },
  {
    order: 12,
    title: "Potencia eléctrica y consumo",
    description: "Calcula la potencia de tus instrumentos, entiende la carga del PLC y evita sobrecargar fuentes de alimentación.",
    durationSec: 300,
    videoPath: `${BASE}/modulo-1-fundamentos/Clase 1.5 - Potencia y consumo.html`,
  },
  {
    order: 13,
    title: "Señales: voltaje, corriente, resistencia",
    description: "Señales de proceso en la industria: 0-5 V, 1-5 V, 4-20 mA y señales RTD. Cuándo usar cada tipo y por qué.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-1-fundamentos/Clase 1.6 - Senales electricas.html`,
  },
  {
    order: 14,
    title: "Introducción a los semiconductores",
    description: "Transistores, optoacopladores y circuitos integrados que forman el corazón de los transmisores y PLCs modernos.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-1-fundamentos/Clase 1.7 - Semiconductores.html`,
  },
  {
    order: 15,
    title: "Laboratorio virtual de circuitos",
    description: "Práctica interactiva: construye lazos 4-20 mA en simulador, mide con multímetro virtual y diagnostica fallas comunes.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-1-fundamentos/Clase 1.8 - Laboratorio virtual.html`,
  },
  // ── MÓDULO 2 — Introducción a la Instrumentación Industrial ──────────
  {
    order: 16,
    title: "¿Qué es la instrumentación?",
    description: "Definición técnica y práctica: medir para controlar. Diferencia entre instrumento primario, transmisor y controlador.",
    durationSec: 300,
    videoPath: `${BASE}/modulo-2-instrumentacion/Clase 2.1 - Que es la instrumentacion.html`,
  },
  {
    order: 17,
    title: "PV, SP y CV: el lazo de control",
    description: "Las tres variables que gobiernan todo proceso: Variable de Proceso, Setpoint y Variable de Control. Visualización animada.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-2-instrumentacion/Clase 2.2 - PV SP CV.html`,
  },
  {
    order: 18,
    title: "Clasificación de instrumentos",
    description: "Instrumentos por función (medición, control, actuación) y por variable (temperatura, presión, nivel, caudal).",
    durationSec: 300,
    videoPath: `${BASE}/modulo-2-instrumentacion/Clase 2.3 - Clasificacion de instrumentos.html`,
  },
  {
    order: 19,
    title: "Señales estándar (4-20 mA, HART)",
    description: "Por qué la industria eligió 4-20 mA: detección de falla, inmunidad al ruido y distancias largas. HART superpuesto.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-2-instrumentacion/Clase 2.4 - Senales estandar.html`,
  },
  {
    order: 20,
    title: "Rangos, spans y calibración",
    description: "LRV, URV, span y cero. Cómo calcular la salida 4-20 mA para cualquier rango y detectar un instrumento descalibrado.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-2-instrumentacion/Clase 2.5 - Rangos spans y calibracion.html`,
  },
  {
    order: 21,
    title: "Documentación industrial",
    description: "Los documentos que todo instrumentista lee: datasheet, manual, hoja de especificación y loop sheet.",
    durationSec: 300,
    videoPath: `${BASE}/modulo-2-instrumentacion/Clase 2.6 - Documentacion industrial.html`,
  },
  {
    order: 22,
    title: "Simbología ISA-5.1",
    description: "Lee P&IDs como un profesional: burbujas de instrumentación, letras de función y líneas de señal según ISA-5.1.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-2-instrumentacion/Clase 2.7 - Simbologia ISA-5.1.html`,
  },
  {
    order: 23,
    title: "Lectura de un P&ID real",
    description: "Analiza un diagrama de proceso e instrumentación real paso a paso: identifica cada instrumento y su función.",
    durationSec: 540,
    videoPath: `${BASE}/modulo-2-instrumentacion/Clase 2.8 - Lectura de un PID real.html`,
  },
  {
    order: 24,
    title: "Campo vs sala de control",
    description: "Qué vive en campo (intemperie, polvo, vibración) vs qué vive en sala de control (DCS, HMI, PLCs). Diferencias críticas.",
    durationSec: 300,
    videoPath: `${BASE}/modulo-2-instrumentacion/Clase 2.9 - Campo vs sala de control.html`,
  },
  {
    order: 25,
    title: "Práctica: P&ID en draw.io",
    description: "Dibuja tu primer P&ID completo usando la simbología ISA-5.1 en draw.io. Lazo de temperatura con controlador PID.",
    durationSec: 600,
    videoPath: `${BASE}/modulo-2-instrumentacion/Clase 2.10 - Practica PID en drawio.html`,
  },
  // ── MÓDULO 3 — Sensores y Transmisores ───────────────────────────────
  {
    order: 26,
    title: "Termopares (J, K, T)",
    description: "Principio Seebeck, tipos J y K, rangos de temperatura, compensación de junta fría y conexión al transmisor.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-3-sensores/Clase 3.1 - Termopares.html`,
  },
  {
    order: 27,
    title: "RTDs y PT100",
    description: "Resistencia vs temperatura en Pt100: configuraciones 2, 3 y 4 hilos, compensación de cable y precisión industrial.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-3-sensores/Clase 3.2 - RTDs y PT100.html`,
  },
  {
    order: 28,
    title: "Termistores e infrarrojo",
    description: "NTC y PTC para rangos cortos de alta precisión. Pirómetros IR para medición sin contacto en hornos y líneas en movimiento.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-3-sensores/Clase 3.3 - Termistores e IR.html`,
  },
  {
    order: 29,
    title: "Tipos de presión",
    description: "Presión absoluta, manométrica, diferencial y vacío. Conversiones entre unidades y cuándo usar cada referencia.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-3-sensores/Clase 3.4 - Tipos de presion.html`,
  },
  {
    order: 30,
    title: "Sensores de presión",
    description: "Piezoeléctrico, capacitivo y piezoresistivo: principios de operación, rangos y selección para cada aplicación.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-3-sensores/Clase 3.5 - Sensores de presion.html`,
  },
  {
    order: 31,
    title: "Transmisor de presión diferencial",
    description: "El instrumento más versátil de la planta: mide presión diferencial, nivel por columna hidrostática y caudal con placa orificio.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-3-sensores/Clase 3.6 - Transmisor DP.html`,
  },
  {
    order: 32,
    title: "Nivel por presión hidrostática",
    description: "Calcula nivel a partir de la presión del fluido en el fondo del tanque. Efecto de la densidad y compensación de temperatura.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-3-sensores/Clase 3.7 - Nivel hidrostatico.html`,
  },
  {
    order: 33,
    title: "Nivel: ultrasónico, radar y flotador",
    description: "Tecnologías de medición de nivel sin contacto y mecánicas: cuándo elegir cada una según el fluido y las condiciones del tanque.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-3-sensores/Clase 3.8 - Nivel ultrasonico radar flotador.html`,
  },
  {
    order: 34,
    title: "Sensores capacitivos de nivel",
    description: "Medición por capacitancia: para sólidos, granulados y líquidos corrosivos donde el radar no funciona bien.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-3-sensores/Clase 3.9 - Nivel capacitivo.html`,
  },
  {
    order: 35,
    title: "Placa orificio y tubo Venturi",
    description: "Medición de caudal por presión diferencial: ecuación de Bernoulli, beta ratio, coeficiente de descarga y cálculo de flujo.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-3-sensores/Clase 3.10 - Placa orificio y Venturi.html`,
  },
  {
    order: 36,
    title: "Caudalímetros modernos",
    description: "Magnéticos, de vórtice, Coriolis y ultrasónicos: principios, ventajas, limitaciones y criterios de selección.",
    durationSec: 540,
    videoPath: `${BASE}/modulo-3-sensores/Clase 3.11 - Caudalimetros.html`,
  },
  {
    order: 37,
    title: "Práctica: selección de instrumentos",
    description: "Ejercicio final del módulo: selecciona el instrumento correcto para 8 casos reales de temperatura, presión, nivel y caudal.",
    durationSec: 600,
    videoPath: `${BASE}/modulo-3-sensores/Clase 3.12 - Practica seleccion.html`,
  },
  // ── MÓDULO 4 — Actuadores y Elementos Finales de Control ─────────────
  {
    order: 38,
    title: "Válvulas de control",
    description: "Regula vs bloquea: las 3 partes de una válvula de control, tipos de cuerpo (globo, mariposa, bola) y condición de falla FC/FO/FL.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-4-actuadores/Clase 4.1 - Valvulas de control.html`,
  },
  {
    order: 39,
    title: "Actuadores y posicionadores",
    description: "Diafragma neumático ATO/ATC, actuadores de pistón y el lazo de posición cerrado con posicionador electro-neumático.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-4-actuadores/Clase 4.2 - Actuadores y posicionadores.html`,
  },
  {
    order: 40,
    title: "Motores eléctricos industriales",
    description: "Campo giratorio animado, deslizamiento, par de arranque y corriente de arranque comparada en motores de inducción trifásicos.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-4-actuadores/Clase 4.3 - Motores electricos.html`,
  },
  {
    order: 41,
    title: "Variadores de frecuencia (VFD)",
    description: "Arquitectura rectificador–bus DC–inversor, control V/f y la ley del cubo: cómo el VFD reduce el consumo energético.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-4-actuadores/Clase 4.4 - Variadores de frecuencia.html`,
  },
  {
    order: 42,
    title: "Bombas, compresores y sopladores",
    description: "Curva de operación, punto de trabajo, NPSH y cavitación. Familias por diferencial de presión y criterios de selección.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-4-actuadores/Clase 4.5 - Bombas compresores sopladores.html`,
  },
  {
    order: 43,
    title: "Relés, contactores y arrancadores",
    description: "El circuito de sello de marcha animado paso a paso: bobina, contactos auxiliares y arrancadores estrella-triángulo.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-4-actuadores/Clase 4.6 - Reles contactores arrancadores.html`,
  },
  {
    order: 44,
    title: "Práctica: dimensionamiento de válvula",
    description: "Calcula el Cv y selecciona la válvula correcta para FCV-201: caudal, densidad, caída de presión y verificación de cavitación.",
    durationSec: 600,
    videoPath: `${BASE}/modulo-4-actuadores/Clase 4.7 - Practica dimensionamiento valvula.html`,
  },
  // ── MÓDULO 5 — Fundamentos de Control de Proceso ─────────────────────
  {
    order: 45,
    title: "Lazo abierto vs lazo cerrado",
    description: "Diferencia entre control en lazo abierto y cerrado con ejemplos reales. Por qué el feedback es indispensable en la industria.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-5-control/Clase 5.1 - Lazo abierto vs cerrado.html`,
  },
  {
    order: 46,
    title: "Diagrama de bloques del lazo",
    description: "Planta, sensor, controlador y actuador como bloques. Función de transferencia, ganancia y respuesta en frecuencia básica.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-5-control/Clase 5.2 - Diagrama de bloques.html`,
  },
  {
    order: 47,
    title: "Control ON-OFF",
    description: "El controlador más simple: histéresis, banda muerta y oscilaciones. Cuándo usarlo y cuándo reemplazarlo por un PID.",
    durationSec: 300,
    videoPath: `${BASE}/modulo-5-control/Clase 5.3 - Control ON-OFF.html`,
  },
  {
    order: 48,
    title: "Control PID desde cero",
    description: "Proporcional, integral y derivativo explicados visualmente. Cómo cada término actúa sobre el error y la salida del controlador.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-5-control/Clase 5.4 - Control PID desde cero.html`,
  },
  {
    order: 49,
    title: "Sintonización de PID",
    description: "Métodos de sintonización: Ziegler-Nichols, Cohen-Coon y ajuste manual. Cómo encontrar Kp, Ti y Td para cada proceso.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-5-control/Clase 5.5 - Sintonizacion de PID.html`,
  },
  {
    order: 50,
    title: "Álgebra booleana y compuertas lógicas",
    description: "AND, OR, NOT, NAND y NOR en contexto industrial. Simplificación de ecuaciones lógicas para enclavamientos de seguridad.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-5-control/Clase 5.6 - Algebra booleana y compuertas.html`,
  },
  {
    order: 51,
    title: "Diagramas Ladder básicos",
    description: "Contactos, bobinas y bloques funcionales en Ladder. Lee e interpreta circuitos de enclavamiento de un compresor real.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-5-control/Clase 5.7 - Diagramas Ladder.html`,
  },
  {
    order: 52,
    title: "Práctica: lazo PID completo",
    description: "Ejercicio integrador: diseña, sintoniza y verifica un lazo de control de temperatura en simulador paso a paso.",
    durationSec: 600,
    videoPath: `${BASE}/modulo-5-control/Clase 5.8 - Practica lazo PID.html`,
  },
  // ── MÓDULO 6 — Controladores Lógicos Programables (PLC) ──────────────
  {
    order: 53,
    title: "¿Qué es un PLC?",
    description: "Historia, arquitectura y ventajas del PLC frente al cableado duro. Ciclo de operación: entrada → lógica → salida.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.1 - Que es un PLC.html`,
  },
  {
    order: 54,
    title: "Partes del PLC (S7-1214C)",
    description: "CPU, módulos de E/S, fuente y rack en el Siemens S7-1200. Identificación de terminales y especificaciones del datasheet.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.2 - Partes del PLC.html`,
  },
  {
    order: 55,
    title: "Entradas y salidas digitales",
    description: "Sinking vs sourcing, niveles de señal 24 VDC, protección de salidas a relé y transistor. Cómo cablear sensores y actuadores.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.3 - Entradas y salidas digitales.html`,
  },
  {
    order: 56,
    title: "Entradas y salidas analógicas",
    description: "Módulos de 4-20 mA y 0-10 V en el PLC. Escalado con NORM_X y SCALE_X, el valor 27648 y diagnóstico de señales.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.4 - Entradas y salidas analogicas.html`,
  },
  {
    order: 57,
    title: "El ciclo de scan del PLC",
    description: "Fases del ciclo: lectura de entradas, ejecución del programa, actualización de salidas y comunicaciones. Tiempos típicos.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.5 - El ciclo de scan.html`,
  },
  {
    order: 58,
    title: "Sistemas de numeración",
    description: "Binario, hexadecimal y BCD aplicados al PLC. Cómo la CPU almacena datos en registros y cómo leerlos en el diagnóstico.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.6 - Sistemas de numeracion.html`,
  },
  {
    order: 59,
    title: "Lenguajes IEC 61131-3",
    description: "Los 5 lenguajes estándar: Ladder, FBD, STL, SFC y SCL. Cuándo usar cada uno y cómo coexisten en un proyecto real.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.7 - Lenguajes IEC 61131-3.html`,
  },
  {
    order: 60,
    title: "Ladder avanzado: timers y contadores",
    description: "TON, TOF, TP y CTU/CTD en acción: circuito de sello, temporización de arranque y conteo de piezas en línea.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.8 - Ladder avanzado.html`,
  },
  {
    order: 61,
    title: "Comparadores y matemáticas",
    description: "Instrucciones CMP, ADD, SUB, MUL, DIV y MOD en Ladder y SCL. Cálculo de eficiencia y alarmas por límites numéricos.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.9 - Comparadores y matematicas.html`,
  },
  {
    order: 62,
    title: "Bloques de función analógica",
    description: "Crea un FB reutilizable AI_Scaling: parámetros IN/OUT, instancias múltiples y prueba en el simulador del TIA Portal.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.10 - Bloques de funcion analogica.html`,
  },
  {
    order: 63,
    title: "Programación estructurada",
    description: "Máquina de estados en SCL para el control de un motor: estados IDLE, RUN, FAULT y transiciones con temporizadores.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.11 - Programacion estructurada.html`,
  },
  {
    order: 64,
    title: "Introducción a TIA Portal",
    description: "Crear proyecto, configurar hardware S7-1214C, compilar y descargar. El entorno de programación Siemens paso a paso.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.12 - Introduccion a TIA Portal.html`,
  },
  {
    order: 65,
    title: "Factory IO + TIA Portal",
    description: "Conecta TIA Portal con Factory IO para simular una línea de producción 3D. Configura OPC y prueba tu Ladder en tiempo real.",
    durationSec: 540,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.13 - Factory IO + TIA Portal.html`,
  },
  {
    order: 66,
    title: "Proyecto PLC 1: control de nivel",
    description: "Control de nivel de tanque con lazo PID en TIA Portal: sensor DP, válvula proporcional, alarmas y trending en HMI.",
    durationSec: 600,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.14 - Proyecto PLC 1.html`,
  },
  {
    order: 67,
    title: "Proyecto PLC 2: planta integrada",
    description: "Proyecto final: planta de tratamiento de agua con secuencia SFC, 4 lazos PID, enclavamientos y reporte de producción.",
    durationSec: 600,
    videoPath: `${BASE}/modulo-6-plc/Clase 6.15 - Proyecto PLC 2.html`,
  },
  // ── Módulo 7 — Redes Industriales y Comunicaciones ──
  {
    order: 68,
    title: "Introducción a redes industriales",
    description: "La pirámide de automatización ISA-95: campo, control, supervisión, MES y ERP. Protocolos por nivel y por qué importa la topología.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-7/Clase 7.1 - Introduccion a redes industriales.html`,
  },
  {
    order: 69,
    title: "Modbus RTU y TCP/IP",
    description: "El protocolo más extendido en la industria: trama RTU byte a byte, función codes 03/06/16, y migración a Modbus TCP sobre Ethernet.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-7/Clase 7.2 - Modbus RTU y TCP.html`,
  },
  {
    order: 70,
    title: "PROFIBUS y PROFINET",
    description: "PROFIBUS DP: maestro/esclavo, GSD, diagnóstico de bus. PROFINET IO: RT y IRT, device model y configuración en TIA Portal.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-7/Clase 7.3 - PROFIBUS y PROFINET.html`,
  },
  {
    order: 71,
    title: "OPC y OPC-UA",
    description: "OPC clásico vs OPC-UA: modelo de información, seguridad con certificados, servidor/cliente UA y conexión a SCADA y MES.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-7/Clase 7.4 - OPC y OPC-UA.html`,
  },
  {
    order: 72,
    title: "Ethernet industrial y seguridad IT/OT",
    description: "Switches gestionados, redundancia MRP/RSTP, VLANs, segmentación IT/OT con DMZ y buenas prácticas de ciberseguridad industrial.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-7/Clase 7.5 - Ethernet industrial.html`,
  },
  {
    order: 73,
    title: "Práctica: Modbus PLC↔HMI",
    description: "Proyecto integrador: servidor MB_SERVER en S7-1200, mini-HMI Node-RED y análisis de tramas con Wireshark. Conecta campo con supervisión.",
    durationSec: 600,
    videoPath: `${BASE}/modulo-7/Clase 7.6 - Practica Modbus PLC-HMI.html`,
  },
  // ── Módulo 8 — SCADA e IIoT ──
  {
    order: 74,
    title: "¿Qué es un SCADA?",
    description: "Historia y arquitectura de los sistemas SCADA: RTU, MTU, HMI y servidor de datos. Diferencias entre SCADA, DCS y PLC y cuándo usar cada uno.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-8/Clase 8.1 - Que es un SCADA.html`,
  },
  {
    order: 75,
    title: "Ignition: instalación y primeros pasos",
    description: "Instala Ignition de Inductive Automation, crea tu primer proyecto y navega por el Designer. Configuración del Gateway y módulos esenciales.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-8/Clase 8.2 - Ignition instalacion.html`,
  },
  {
    order: 76,
    title: "Tags en Ignition",
    description: "Tag Provider, tipos de tags (OPC, Memory, Expression, Query), UDTs y organización en carpetas. El corazón del modelo de datos en Ignition.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-8/Clase 8.3 - Tags en Ignition.html`,
  },
  {
    order: 77,
    title: "Conexión OPC-UA",
    description: "Conecta Ignition a un PLC S7-1200 vía OPC-UA: configura el servidor OPC, explora el address space y enlaza tags al proyecto SCADA.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-8/Clase 8.4 - Conexion OPC-UA.html`,
  },
  {
    order: 78,
    title: "Sinópticos y ASM",
    description: "Diseña pantallas de proceso siguiendo la filosofía ASM (Abnormal Situation Management): jerarquía de vistas, navegación y componentes clave.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-8/Clase 8.5 - Sinopticos ASM.html`,
  },
  {
    order: 79,
    title: "Sistema de alarmas",
    description: "Configura alarmas en Ignition: prioridades, estados (activa, reconocida, resuelta), pipelines de notificación y journal de alarmas histórico.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-8/Clase 8.6 - Sistema de alarmas.html`,
  },
  {
    order: 80,
    title: "Tendencias históricas",
    description: "Tag Historian y módulo de Trending: almacena datos de proceso, configura la base de datos y crea gráficas de tendencia en tiempo real e histórico.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-8/Clase 8.7 - Tendencias historicas.html`,
  },
  {
    order: 81,
    title: "Scripting con Python",
    description: "Jython en Ignition: scripts de gateway, de componente y scheduled. Automatiza reportes, calcula KPIs y manipula tags con código Python.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-8/Clase 8.8 - Scripting Python.html`,
  },
  {
    order: 82,
    title: "Reportes en Ignition",
    description: "Módulo Reporting: diseña plantillas con tablas dinámicas, gráficas y parámetros. Genera PDF automáticos por turno y envía por correo.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-8/Clase 8.9 - Reportes.html`,
  },
  {
    order: 83,
    title: "Seguridad y roles",
    description: "Identity Provider, roles y zonas de seguridad en Ignition. Autenticación AD/LDAP, auditoría de acciones y cumplimiento 21 CFR Parte 11.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-8/Clase 8.10 - Seguridad y roles.html`,
  },
  {
    order: 84,
    title: "Práctica: SCADA completo",
    description: "Proyecto integrador: planta de mezcla con PLC S7-1200, OPC-UA, sinópticos ASM, alarmas, historian y reporte PDF automático en Ignition.",
    durationSec: 600,
    videoPath: `${BASE}/modulo-8/Clase 8.11 - Practica SCADA completo.html`,
  },
  {
    order: 85,
    title: "Cloud IIoT y Gemelos Digitales",
    description: "MQTT Sparkplug B, brokers en la nube, Digital Twins con Ignition y AWS IoT. La evolución del SCADA hacia la Industria 4.0.",
    durationSec: 480,
    videoPath: `${BASE}/modulo-8/Clase 8.12 - Cloud IIoT y Gemelos.html`,
  },
  // ── Módulo 9 — Seguridad Eléctrica e Industrial ──
  {
    order: 86,
    title: "Riesgos eléctricos",
    description: "Efectos de la corriente en el cuerpo humano, arco eléctrico, categorías de incidente y distancias de seguridad según NFPA 70E e IEEE 1584.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-9/Clase 9.1 - Riesgos electricos.html`,
  },
  {
    order: 87,
    title: "LOTO y trabajo en altura",
    description: "Procedimiento de Bloqueo/Etiquetado (LOTO) paso a paso, permisos de trabajo, trabajo en altura y andamios seguros en planta industrial.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-9/Clase 9.2 - LOTO y trabajo en altura.html`,
  },
  {
    order: 88,
    title: "Atmósferas peligrosas",
    description: "Clasificación de áreas ATEX/NEC: zonas 0-2 y divisiones 1-2, equipos Ex-d/Ex-e/Ex-i, gas detectors y purga de recintos.",
    durationSec: 360,
    videoPath: `${BASE}/modulo-9/Clase 9.3 - Atmosferas peligrosas.html`,
  },
  {
    order: 89,
    title: "EPP y primeros auxilios eléctricos",
    description: "Selección de EPP dieléctrico por categoría de arco, RCP y protocolo ante electrocución, desfibrilador y reporte de incidentes.",
    durationSec: 300,
    videoPath: `${BASE}/modulo-9/Clase 9.4 - EPP y primeros auxilios.html`,
  },
  {
    order: 90,
    title: "Normativa SIL y Sistemas SIS",
    description: "IEC 61508/61511: niveles de integridad de seguridad (SIL), PFD, arquitecturas redundantes y validación de Sistemas Instrumentados de Seguridad.",
    durationSec: 420,
    videoPath: `${BASE}/modulo-9/Clase 9.5 - Normativa SIL SIS.html`,
  },
];

const totalSec = lessons.reduce((s, l) => s + l.durationSec, 0);
const totalMinutes = Math.round(totalSec / 60);

async function main() {
  await prisma.lesson.deleteMany();
  await prisma.course.deleteMany();

  await prisma.course.create({
    data: {
      slug: "instrumentacion-industrial",
      title: "Instrumentación y Automatización Industrial",
      description:
        "Domina la instrumentación industrial de cero a profesional. Siete módulos progresivos: fundamentos de electricidad y física, lectura de P&IDs, señales estándar, sensores, actuadores, control PID y PLCs Siemens — con animaciones interactivas.",
      instructor: "Instrumex",
      level: "Principiante",
      category: "Ingeniería Industrial",
      totalMinutes,
      lessonCount: lessons.length,
      lessons: { create: lessons },
    },
  });

  console.log(`✅ Seed completado: ${lessons.length} lecciones, ${totalMinutes} minutos`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
